### ISSUE TITLE
Nested labels are missing the open chevron button

### ISSUE THREAD

**Issue by grinich** [taniadaniela/n1-agapanthus#8]
![screen shot 2016-05-10 at 1 58 49 pm](https://cloud.githubusercontent.com/assets/92417/15162386/73910b12-16b7-11e6-9b1e-9b5b2d596fe1.png)
![screen shot 2016-05-10 at 1 59 21 pm](https://cloud.githubusercontent.com/assets/92417/15162387/739e0844-16b7-11e6-8dfb-4a4552b267b2.png)

This is needed to open sublabels and subfolders.

**Comment by taniadaniela** [comment]
@grinich Hi, thanks for the feedback. I've already fixed this issue if you want to try it again and we can close this issue.

**Comment by grinich** [comment]
thanks for the quick fix!
