### ISSUE TITLE
Unread dot doesn't show unless i am hovering

### ISSUE THREAD

**Issue by grinich** [taniadaniela/n1-agapanthus#9]
![image](https://cloud.githubusercontent.com/assets/92417/15164141/c339cc4e-16c1-11e6-8399-673c83d989b9.png)

both of these are unread but i'm hovering on the bottom one

**Comment by taniadaniela** [comment]
Fixed.. Please test it to close the issue.
Btw, I'm having the same issue on Taiga too..
